// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Certificate struct {
	TokenID       string
	OwnerAddress  string
	Title         string
	RecipientName string
	IssuerName    string
	Description   string
	MetadataUri   string
	IssuedAt      pgtype.Timestamptz
	ChainID       int64
	TxHash        string
	LogIndex      int64
	BlockNumber   int64
	BlockHash     string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type IndexerState struct {
	ID                 int32
	ChainID            int64
	LastProcessedBlock int64
	LastProcessedHash  string
	UpdatedAt          pgtype.Timestamptz
}
