// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCertificates = `-- name: CountCertificates :one
SELECT count(*) FROM certificates
`

// CountCertificates returns the total number of certificates (for indexer status).
func (q *Queries) CountCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCertificatesFromBlock = `-- name: DeleteCertificatesFromBlock :exec
DELETE FROM certificates WHERE chain_id = $1 AND block_number >= $2
`

type DeleteCertificatesFromBlockParams struct {
	ChainID     int64
	BlockNumber int64
}

// DeleteCertificatesFromBlock removes all certificates at or above the given block number
// (chain-scoped) — used by reorg reconcile to roll back the confirmation window.
func (q *Queries) DeleteCertificatesFromBlock(ctx context.Context, arg DeleteCertificatesFromBlockParams) error {
	_, err := q.db.Exec(ctx, deleteCertificatesFromBlock, arg.ChainID, arg.BlockNumber)
	return err
}

const getCertificateByTokenID = `-- name: GetCertificateByTokenID :one
SELECT token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at FROM certificates WHERE token_id = $1
`

// GetCertificateByTokenID fetches a certificate by its primary key.
func (q *Queries) GetCertificateByTokenID(ctx context.Context, tokenID string) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByTokenID, tokenID)
	var i Certificate
	err := row.Scan(
		&i.TokenID,
		&i.OwnerAddress,
		&i.Title,
		&i.RecipientName,
		&i.IssuerName,
		&i.Description,
		&i.MetadataUri,
		&i.IssuedAt,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.BlockNumber,
		&i.BlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndexerState = `-- name: GetIndexerState :one
SELECT id, chain_id, last_processed_block, last_processed_hash, updated_at FROM indexer_state WHERE id = 1
`

// GetIndexerState fetches the singleton indexer progress row.
func (q *Queries) GetIndexerState(ctx context.Context) (IndexerState, error) {
	row := q.db.QueryRow(ctx, getIndexerState)
	var i IndexerState
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.LastProcessedBlock,
		&i.LastProcessedHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
SELECT token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at FROM certificates
WHERE ($1::numeric IS NULL OR token_id < $1)
ORDER BY token_id DESC
LIMIT $2
`

type ListCertificatesParams struct {
	Column1 pgtype.Numeric
	Limit   int32
}

// ListCertificates returns certificates via keyset pagination (token_id DESC).
// Passing NULL cursor returns the first page.
func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificates, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.TokenID,
			&i.OwnerAddress,
			&i.Title,
			&i.RecipientName,
			&i.IssuerName,
			&i.Description,
			&i.MetadataUri,
			&i.IssuedAt,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByOwner = `-- name: ListCertificatesByOwner :many
SELECT token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at FROM certificates
WHERE owner_address = $1
  AND ($2::numeric IS NULL OR token_id < $2)
ORDER BY token_id DESC
LIMIT $3
`

type ListCertificatesByOwnerParams struct {
	OwnerAddress string
	Column2      pgtype.Numeric
	Limit        int32
}

// ListCertificatesByOwner returns certificates for a given owner via keyset pagination.
// Uses idx_certificates_owner_token (owner_address, token_id DESC).
func (q *Queries) ListCertificatesByOwner(ctx context.Context, arg ListCertificatesByOwnerParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByOwner, arg.OwnerAddress, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.TokenID,
			&i.OwnerAddress,
			&i.Title,
			&i.RecipientName,
			&i.IssuerName,
			&i.Description,
			&i.MetadataUri,
			&i.IssuedAt,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCertificates = `-- name: SearchCertificates :many
SELECT token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at FROM certificates
WHERE (title ILIKE '%' || $1 || '%'
    OR issuer_name ILIKE '%' || $1 || '%'
    OR recipient_name ILIKE '%' || $1 || '%')
  AND ($2::numeric IS NULL OR token_id < $2)
ORDER BY token_id DESC
LIMIT $3
`

type SearchCertificatesParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Numeric
	Limit   int32
}

// SearchCertificates full-text searches title/issuer_name/recipient_name with keyset pagination.
// ponytail: ILIKE scan; add pg_trgm GIN index when n grows
func (q *Queries) SearchCertificates(ctx context.Context, arg SearchCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, searchCertificates, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.TokenID,
			&i.OwnerAddress,
			&i.Title,
			&i.RecipientName,
			&i.IssuerName,
			&i.Description,
			&i.MetadataUri,
			&i.IssuedAt,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCertificatesByOwner = `-- name: SearchCertificatesByOwner :many
SELECT token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at FROM certificates
WHERE owner_address = $1
  AND (title ILIKE '%' || $2 || '%'
    OR issuer_name ILIKE '%' || $2 || '%'
    OR recipient_name ILIKE '%' || $2 || '%')
  AND ($3::numeric IS NULL OR token_id < $3)
ORDER BY token_id DESC
LIMIT $4
`

type SearchCertificatesByOwnerParams struct {
	OwnerAddress string
	Column2      pgtype.Text
	Column3      pgtype.Numeric
	Limit        int32
}

// SearchCertificatesByOwner searches title/issuer_name/recipient_name for a given owner with keyset pagination.
// Uses idx_certificates_owner_token (owner_address, token_id DESC).
// ponytail: ILIKE scan; add pg_trgm GIN index when n grows
func (q *Queries) SearchCertificatesByOwner(ctx context.Context, arg SearchCertificatesByOwnerParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, searchCertificatesByOwner,
		arg.OwnerAddress,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.TokenID,
			&i.OwnerAddress,
			&i.Title,
			&i.RecipientName,
			&i.IssuerName,
			&i.Description,
			&i.MetadataUri,
			&i.IssuedAt,
			&i.ChainID,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCertificate = `-- name: UpsertCertificate :one
INSERT INTO certificates (
    token_id, owner_address, title, recipient_name, issuer_name,
    description, metadata_uri, issued_at, chain_id, tx_hash,
    log_index, block_number, block_hash, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, now(), now()
)
ON CONFLICT (token_id) DO UPDATE SET
    owner_address  = EXCLUDED.owner_address,
    title          = EXCLUDED.title,
    recipient_name = EXCLUDED.recipient_name,
    issuer_name    = EXCLUDED.issuer_name,
    description    = EXCLUDED.description,
    metadata_uri   = EXCLUDED.metadata_uri,
    issued_at      = EXCLUDED.issued_at,
    chain_id       = EXCLUDED.chain_id,
    tx_hash        = EXCLUDED.tx_hash,
    log_index      = EXCLUDED.log_index,
    block_number   = EXCLUDED.block_number,
    block_hash     = EXCLUDED.block_hash,
    updated_at     = now()
RETURNING token_id, owner_address, title, recipient_name, issuer_name, description, metadata_uri, issued_at, chain_id, tx_hash, log_index, block_number, block_hash, created_at, updated_at
`

type UpsertCertificateParams struct {
	TokenID       string
	OwnerAddress  string
	Title         string
	RecipientName string
	IssuerName    string
	Description   string
	MetadataUri   string
	IssuedAt      pgtype.Timestamptz
	ChainID       int64
	TxHash        string
	LogIndex      int64
	BlockNumber   int64
	BlockHash     string
}

// UpsertCertificate inserts or updates a certificate row by token_id.
// Idempotent: re-processing the same event updates canonical tx/block (reorg guard).
func (q *Queries) UpsertCertificate(ctx context.Context, arg UpsertCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, upsertCertificate,
		arg.TokenID,
		arg.OwnerAddress,
		arg.Title,
		arg.RecipientName,
		arg.IssuerName,
		arg.Description,
		arg.MetadataUri,
		arg.IssuedAt,
		arg.ChainID,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.BlockHash,
	)
	var i Certificate
	err := row.Scan(
		&i.TokenID,
		&i.OwnerAddress,
		&i.Title,
		&i.RecipientName,
		&i.IssuerName,
		&i.Description,
		&i.MetadataUri,
		&i.IssuedAt,
		&i.ChainID,
		&i.TxHash,
		&i.LogIndex,
		&i.BlockNumber,
		&i.BlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIndexerState = `-- name: UpsertIndexerState :one
INSERT INTO indexer_state (id, chain_id, last_processed_block, last_processed_hash, updated_at)
VALUES (1, $1, $2, $3, now())
ON CONFLICT (id) DO UPDATE SET
    chain_id             = EXCLUDED.chain_id,
    last_processed_block = EXCLUDED.last_processed_block,
    last_processed_hash  = EXCLUDED.last_processed_hash,
    updated_at           = now()
RETURNING id, chain_id, last_processed_block, last_processed_hash, updated_at
`

type UpsertIndexerStateParams struct {
	ChainID            int64
	LastProcessedBlock int64
	LastProcessedHash  string
}

// UpsertIndexerState inserts or updates the singleton indexer progress row.
func (q *Queries) UpsertIndexerState(ctx context.Context, arg UpsertIndexerStateParams) (IndexerState, error) {
	row := q.db.QueryRow(ctx, upsertIndexerState, arg.ChainID, arg.LastProcessedBlock, arg.LastProcessedHash)
	var i IndexerState
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.LastProcessedBlock,
		&i.LastProcessedHash,
		&i.UpdatedAt,
	)
	return i, err
}
